services:
  - type: web
    name: gujarati-marketplace-germany-backend
    runtime: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production